baseurl = "/"
languageCode = "en-us"
title = "COGMO website"
theme = "indigo"
googleAnalytics = ""
#disqusShortname = "COGMO"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About COGMO"
    url = "/about/"
[[menu.main]]
    name = "Our doctors"
    url ="/doctors/"
[[menu.main]]
    name = "Referrals"
    url = "/referrals/"
[[menu.main]]
    name = "Contacts"
    url = "/contacts/"
[[menu.main]]
    name = "Useful links"
    url = "/links/"

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    #favicon = "favicon.ico"
    favicon = "ddembe.jpg"

    [params.logo]
    url = "ddembe.jpg"
    width = 50
    height = 50
    alt = "COGMO Blog"

